// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Card interface {
	IsCard()
	GetID() string
	GetName() string
	GetCost() int32
	GetInkwell() bool
	GetInk() Ink
	GetClassifications() []Classification
	GetRarity() Rarity
	GetSet() int32
	GetNumber() int32
}

type Ability struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Common      bool   `json:"common"`
}

type Action struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	Cost             int32            `json:"cost"`
	Inkwell          bool             `json:"inkwell"`
	Ink              Ink              `json:"ink"`
	Classifications  []Classification `json:"classifications"`
	Rarity           Rarity           `json:"rarity"`
	Set              int32            `json:"set"`
	Number           int32            `json:"number"`
	Description      string           `json:"description"`
	SingTogetherCost *int32           `json:"singTogetherCost,omitempty"`
}

func (Action) IsCard()               {}
func (this Action) GetID() string    { return this.ID }
func (this Action) GetName() string  { return this.Name }
func (this Action) GetCost() int32   { return this.Cost }
func (this Action) GetInkwell() bool { return this.Inkwell }
func (this Action) GetInk() Ink      { return this.Ink }
func (this Action) GetClassifications() []Classification {
	if this.Classifications == nil {
		return nil
	}
	interfaceSlice := make([]Classification, 0, len(this.Classifications))
	for _, concrete := range this.Classifications {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Action) GetRarity() Rarity { return this.Rarity }
func (this Action) GetSet() int32     { return this.Set }
func (this Action) GetNumber() int32  { return this.Number }

type Character struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Cost            int32            `json:"cost"`
	Inkwell         bool             `json:"inkwell"`
	Ink             Ink              `json:"ink"`
	Classifications []Classification `json:"classifications"`
	Rarity          Rarity           `json:"rarity"`
	Set             int32            `json:"set"`
	Number          int32            `json:"number"`
	Version         string           `json:"version"`
	Strength        int32            `json:"strength"`
	Willpower       int32            `json:"willpower"`
	LoreValue       *int32           `json:"loreValue,omitempty"`
	Abilities       []*Ability       `json:"abilities,omitempty"`
}

func (Character) IsCard()               {}
func (this Character) GetID() string    { return this.ID }
func (this Character) GetName() string  { return this.Name }
func (this Character) GetCost() int32   { return this.Cost }
func (this Character) GetInkwell() bool { return this.Inkwell }
func (this Character) GetInk() Ink      { return this.Ink }
func (this Character) GetClassifications() []Classification {
	if this.Classifications == nil {
		return nil
	}
	interfaceSlice := make([]Classification, 0, len(this.Classifications))
	for _, concrete := range this.Classifications {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Character) GetRarity() Rarity { return this.Rarity }
func (this Character) GetSet() int32     { return this.Set }
func (this Character) GetNumber() int32  { return this.Number }

type Query struct {
}

type Classification string

const (
	ClassificationItem      Classification = "ITEM"
	ClassificationAction    Classification = "ACTION"
	ClassificationSong      Classification = "SONG"
	ClassificationLocation  Classification = "LOCATION"
	ClassificationStoryborn Classification = "STORYBORN"
	ClassificationDreamborn Classification = "DREAMBORN"
	ClassificationFloodborn Classification = "FLOODBORN"
	ClassificationHero      Classification = "HERO"
	ClassificationVillain   Classification = "VILLAIN"
	ClassificationAlly      Classification = "ALLY"
	ClassificationAlien     Classification = "ALIEN"
	ClassificationCaptain   Classification = "CAPTAIN"
	ClassificationHunny     Classification = "HUNNY"
	ClassificationKing      Classification = "KING"
	ClassificationKnight    Classification = "KNIGHT"
	ClassificationMadrigal  Classification = "MADRIGAL"
	ClassificationMentor    Classification = "MENTOR"
	ClassificationMonster   Classification = "MONSTER"
	ClassificationPrince    Classification = "PRINCE"
	ClassificationPrincess  Classification = "PRINCESS"
	ClassificationQueen     Classification = "QUEEN"
	ClassificationRedPanda  Classification = "RED_PANDA"
	ClassificationSorcerer  Classification = "SORCERER"
	ClassificationTeam      Classification = "TEAM"
	ClassificationToy       Classification = "TOY"
	ClassificationVineling  Classification = "VINELING"
	ClassificationOther     Classification = "OTHER"
)

var AllClassification = []Classification{
	ClassificationItem,
	ClassificationAction,
	ClassificationSong,
	ClassificationLocation,
	ClassificationStoryborn,
	ClassificationDreamborn,
	ClassificationFloodborn,
	ClassificationHero,
	ClassificationVillain,
	ClassificationAlly,
	ClassificationAlien,
	ClassificationCaptain,
	ClassificationHunny,
	ClassificationKing,
	ClassificationKnight,
	ClassificationMadrigal,
	ClassificationMentor,
	ClassificationMonster,
	ClassificationPrince,
	ClassificationPrincess,
	ClassificationQueen,
	ClassificationRedPanda,
	ClassificationSorcerer,
	ClassificationTeam,
	ClassificationToy,
	ClassificationVineling,
	ClassificationOther,
}

func (e Classification) IsValid() bool {
	switch e {
	case ClassificationItem, ClassificationAction, ClassificationSong, ClassificationLocation, ClassificationStoryborn, ClassificationDreamborn, ClassificationFloodborn, ClassificationHero, ClassificationVillain, ClassificationAlly, ClassificationAlien, ClassificationCaptain, ClassificationHunny, ClassificationKing, ClassificationKnight, ClassificationMadrigal, ClassificationMentor, ClassificationMonster, ClassificationPrince, ClassificationPrincess, ClassificationQueen, ClassificationRedPanda, ClassificationSorcerer, ClassificationTeam, ClassificationToy, ClassificationVineling, ClassificationOther:
		return true
	}
	return false
}

func (e Classification) String() string {
	return string(e)
}

func (e *Classification) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Classification(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Classification", str)
	}
	return nil
}

func (e Classification) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Classification) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Classification) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Ink string

const (
	InkAmber    Ink = "AMBER"
	InkAmethyst Ink = "AMETHYST"
	InkEmerald  Ink = "EMERALD"
	InkRuby     Ink = "RUBY"
	InkSapphire Ink = "SAPPHIRE"
	InkSteel    Ink = "STEEL"
)

var AllInk = []Ink{
	InkAmber,
	InkAmethyst,
	InkEmerald,
	InkRuby,
	InkSapphire,
	InkSteel,
}

func (e Ink) IsValid() bool {
	switch e {
	case InkAmber, InkAmethyst, InkEmerald, InkRuby, InkSapphire, InkSteel:
		return true
	}
	return false
}

func (e Ink) String() string {
	return string(e)
}

func (e *Ink) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Ink(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Ink", str)
	}
	return nil
}

func (e Ink) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Ink) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Ink) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Rarity string

const (
	RarityCommon    Rarity = "COMMON"
	RarityUncommon  Rarity = "UNCOMMON"
	RarityRare      Rarity = "RARE"
	RaritySuperRare Rarity = "SUPER_RARE"
	RarityLegendary Rarity = "LEGENDARY"
	RarityEpic      Rarity = "EPIC"
	RarityEnchanted Rarity = "ENCHANTED"
	RarityIconic    Rarity = "ICONIC"
)

var AllRarity = []Rarity{
	RarityCommon,
	RarityUncommon,
	RarityRare,
	RaritySuperRare,
	RarityLegendary,
	RarityEpic,
	RarityEnchanted,
	RarityIconic,
}

func (e Rarity) IsValid() bool {
	switch e {
	case RarityCommon, RarityUncommon, RarityRare, RaritySuperRare, RarityLegendary, RarityEpic, RarityEnchanted, RarityIconic:
		return true
	}
	return false
}

func (e Rarity) String() string {
	return string(e)
}

func (e *Rarity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Rarity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Rarity", str)
	}
	return nil
}

func (e Rarity) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Rarity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Rarity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
