package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/tduong2049/lorcana-graphql/internal/graph/model"
)

// Cards is the resolver for the cards field.
func (r *queryResolver) Cards(ctx context.Context) ([]model.Card, error) {
	panic(fmt.Errorf("not implemented: Cards - cards"))
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]*model.Character, error) {
	panic(fmt.Errorf("not implemented: Characters - characters"))
}

// Actions is the resolver for the actions field.
func (r *queryResolver) Actions(ctx context.Context) ([]*model.Action, error) {
	panic(fmt.Errorf("not implemented: Actions - actions"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
