### Interfaces

interface Card {
  id: ID!
  name: String!
  cost: Int!
  inkwell: Boolean!
  ink: Ink!
  classifications: [Classification!]!
  rarity: Rarity!
  set: Int!
  number: Int!
}

### Types

type Character implements Card {
  id: ID!
  name: String!
  cost: Int!
  inkwell: Boolean!
  ink: Ink!
  classifications: [Classification!]!
  rarity: Rarity!
  set: Int!
  number: Int!

  version: String! # Version / Variant / Title
  strength: Int!
  willpower: Int!
  loreValue: Int!
  abilities: [Ability!]
}

type Action implements Card {
  id: ID!
  name: String!
  cost: Int!
  inkwell: Boolean!
  ink: Ink!
  classifications: [Classification!]!
  rarity: Rarity!
  set: Int!
  number: Int!

  description: String!
  singTogetherCost: Int
}

type Location implements Card {
  id: ID!
  name: String!
  cost: Int!
  inkwell: Boolean!
  ink: Ink!
  classifications: [Classification!]!
  rarity: Rarity!
  set: Int!
  number: Int!

  willpower: Int!
  loreValue: Int!
  moveCost: Int!
  abilities: [Ability!]
}

type Ability {
  id: ID!
  name: String!
  description: String!
  keyword: Boolean! # True for common abilities such as Bodyguard, Reckless, Evasive, etc.
}

### Enums

enum Ink {
  AMBER
  AMETHYST
  EMERALD
  RUBY
  SAPPHIRE
  STEEL
}

enum Rarity {
  COMMON
  UNCOMMON
  RARE
  SUPER_RARE
  LEGENDARY
  EPIC
  ENCHANTED
  ICONIC
}

enum Classification {
  ITEM
  ACTION
  SONG
  LOCATION

  STORYBORN
  DREAMBORN
  FLOODBORN

  HERO
  VILLAIN
  ALLY

  ALIEN
  CAPTAIN
  HUNNY
  HYPERIA_CITY
  KING
  KNIGHT
  MADRIGAL
  MENTOR
  MONSTER
  PRINCE
  PRINCESS
  QUEEN
  RED_PANDA
  SORCERER
  TEAM
  TOY
  VINELING

  OTHER # Placeholder until official names are added.
}

### Queries

type Query {
  cards(filter: CardsFilter): [Card!]!
  characters(filter: CharactersFilter): [Character!]!
  actions(filter: ActionsFilter): [Action!]!
  locations(filter: LocationsFilter): [Location!]!
}

### Query Inputs

input CardsFilter {
  ids: [ID!]
  names: [String!]
  costs: [Int!]
  inkwell: Boolean
  inks: [Ink!]
  classifications: [Classification!]
  rarities: [Rarity!]
  sets: [Int!]
}

input CharactersFilter {
  ids: [ID!]
  names: [String!]
  costs: [Int!]
  inkwell: Boolean
  inks: [Ink!]
  classifications: [Classification!]
  rarities: [Rarity!]
  sets: [Int!]

  versions: [String!]
  strengths: [Int!]
  willpower: [Int!]
  loreValues: [Int!]
  abilities: AbilitiesFilter
}

input ActionsFilter {
  ids: [ID!]
  names: [String!]
  costs: [Int!]
  inkwell: Boolean
  inks: [Ink!]
  classifications: [Classification!]
  rarities: [Rarity!]
  sets: [Int!]

  descriptions: [String!]
  singTogetherCosts: [Int!]
}

input LocationsFilter {
  ids: [ID!]
  names: [String!]
  costs: [Int!]
  inkwell: Boolean
  inks: [Ink!]
  classifications: [Classification!]
  rarities: [Rarity!]
  sets: [Int!]

  willpower: [Int!]
  loreValues: [Int!]
  moveCosts: [Int!]
  abilities: AbilitiesFilter
}

input AbilitiesFilter {
  ids: [ID!]
  names: [String!]
  descriptions: [String!]
  keyword: Boolean
}

### Mutations

### Mutation Inputs